apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus-operator
  labels:
    app: grafana-lb
  annotations:
    loadbalancer.openstack.org/keep-floatingip: "true"
    loadbalancer.openstack.org/x-forwarded-for: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000